


interface LayoutProps {
    children: React.ReactNode;
    params: any;
  }


export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}



const Layout: React.FC<LayoutProps> = ({ children, params }) => {
    return (
        <main>
            <div>
                
                    {children}
                
            </div>
        </main>
    )
  };
  
  export default Layout;
